export const allergyFilterMap = {
  no_egg: "계란",
  no_milk: "우유",
  no_buckwheat: "메밀",
  no_peanut: "땅콩",
  no_soy: "대두",
  no_wheat: "밀",
  no_mackerel: "고등어",
  no_crab: "게",
  no_shrimp: "새우",
  no_squid: "오징어",
  no_oyster: "굴",
  no_abalone: "전복",
  no_mussel: "홍합",
  no_walnut: "호두",
  no_almond: "아몬드",
  no_pinenut: "잣",
  no_peach: "복숭아",
  no_tomato: "토마토",
} as const;

export const allergyFilterMapReversed: Record<string, string> = {
  계란: "no_egg",
  우유: "no_milk",
  메밀: "no_buckwheat",
  땅콩: "no_peanut",
  대두: "no_soy",
  밀: "no_wheat",
  고등어: "no_mackerel",
  게: "no_crab",
  새우: "no_shrimp",
  오징어: "no_squid",
  굴: "no_oyster",
  전복: "no_abalone",
  홍합: "no_mussel",
  호두: "no_walnut",
  아몬드: "no_almond",
  잣: "no_pinenut",
  복숭아: "no_peach",
  토마토: "no_tomato",
  glutenfree: "glutenfree",
  lacto: "lacto",
  ovo: "ovo",
} as const;
